"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useDashboard } from "@/context/DashboardContext";
import { BackendGradeLevel, BackendSection, BackendSubject, createGradeLevel, createSection, createSubject, updateSection, updateSubject, dashboardErrorMessage, fetchAcademicStructure } from "@/lib/dashboardApi";
import { BookOpen, Edit3, Plus, Users, X } from "lucide-react";

export default function AcademicPage(){
 const {teachers,showToast,apiStatus,hasApiPermission}=useDashboard();
 const canManage=hasApiPermission("academic.manage");
 const [levels,setLevels]=useState<BackendGradeLevel[]>([]); const [selectedLevelId,setSelectedLevelId]=useState(""); const [modal,setModal]=useState<"level"|"section"|"subject"|null>(null);
 const [editingSectionId,setEditingSectionId]=useState<string|null>(null); const [editingSubjectId,setEditingSubjectId]=useState<string|null>(null);
 const [levelName,setLevelName]=useState(""); const [levelCode,setLevelCode]=useState("");
 const [sectionName,setSectionName]=useState(""); const [sectionCode,setSectionCode]=useState(""); const [room,setRoom]=useState(""); const [capacity,setCapacity]=useState("35"); const [homeroom,setHomeroom]=useState("");
 const [subjectName,setSubjectName]=useState(""); const [subjectCode,setSubjectCode]=useState(""); const [weeklyPeriods,setWeeklyPeriods]=useState("5");
 const load=useCallback(async()=>{if(apiStatus!=="live")return;try{const s=await fetchAcademicStructure();const next=s.grade_levels??[];setLevels(next);setSelectedLevelId(current=>current&&next.some(l=>String(l.id)===current)?current:String(next[0]?.id??""));}catch(error){showToast("الهيكل الأكاديمي",dashboardErrorMessage(error),"error")}},[apiStatus,showToast]);
 useEffect(()=>{void load()},[load]);
 const level=useMemo(()=>levels.find(l=>String(l.id)===selectedLevelId)??levels[0], [levels,selectedLevelId]);
 async function saveLevel(){if(!levelName.trim()||!levelCode.trim())return;try{const created=await createGradeLevel({name:levelName.trim(),code:levelCode.trim(),sort_order:levels.length+1});setModal(null);setLevelName("");setLevelCode("");await load();setSelectedLevelId(String(created.id));}catch(error){showToast("إضافة مستوى",dashboardErrorMessage(error),"error")}}
 async function saveSection(){if(!level||!sectionName.trim()||!sectionCode.trim())return;try{const body={grade_level_id:String(level.id),name:sectionName.trim(),code:sectionCode.trim(),room_number:room.trim()||null,capacity:Number(capacity)||null,homeroom_teacher_id:homeroom||null}; if(editingSectionId) await updateSection(editingSectionId,body); else await createSection(body); setModal(null);setEditingSectionId(null);setSectionName("");setSectionCode("");setRoom("");setHomeroom("");await load();showToast(editingSectionId?"تم تحديث الشعبة":"تمت إضافة الشعبة","تم حفظ بيانات الشعبة.","success");}catch(error){showToast(editingSectionId?"تعديل شعبة":"إضافة شعبة",dashboardErrorMessage(error),"error")}}
 async function saveSubject(){if(!level||!subjectName.trim()||!subjectCode.trim())return;try{const body={name:subjectName.trim(),code:subjectCode.trim(),grade_level_ids:[String(level.id)],weekly_periods:Number(weeklyPeriods)||null}; if(editingSubjectId) await updateSubject(editingSubjectId,body); else await createSubject(body); setModal(null);setEditingSubjectId(null);setSubjectName("");setSubjectCode("");await load();showToast(editingSubjectId?"تم تحديث المادة":"تمت إضافة المادة","تم حفظ بيانات المادة.","success");}catch(error){showToast(editingSubjectId?"تعديل مادة":"إضافة مادة",dashboardErrorMessage(error),"error")}}
 function teacherName(id?:string|number|null){return teachers.find(t=>t.id===String(id))?.name??"غير معيّن"}
 function editSection(s:BackendSection){setEditingSectionId(String(s.id));setSectionName(s.name??"");setSectionCode(s.code??"");setRoom(s.room_number??"");setCapacity(String(s.capacity??35));setHomeroom(s.homeroom_teacher_id?String(s.homeroom_teacher_id):"");setModal("section")}
 function editSubject(s:BackendSubject){setEditingSubjectId(String(s.id));setSubjectName(s.name??"");setSubjectCode(s.code??"");setWeeklyPeriods(String(s.weekly_periods??5));setModal("subject")}
 function closeModal(){setModal(null);setEditingSectionId(null);setEditingSubjectId(null)}
 return <div className="dashboard-shell"><Sidebar/><div className="main-content"><Header title="الفصول والمواد الدراسية" subtitle="إدارة المستويات والشُعب والقاعات ومربي الفصل وعدد الحصص الأسبوعية للمواد"/><main className="page-body">
  {apiStatus!=="live"?<div className="card" style={{padding:24}}>سجّل الدخول لإدارة الهيكل الأكاديمي الحقيقي.</div>:<>
   <div className="filter-toolbar" style={{marginBottom:16}}><select className="form-select" value={selectedLevelId} onChange={(e)=>setSelectedLevelId(e.target.value)}><option value="">اختر المستوى الدراسي</option>{levels.map(l=><option key={String(l.id)} value={String(l.id)}>{l.name}</option>)}</select>{canManage&&<button className="btn btn-outline" onClick={()=>setModal("level")} title="إضافة مستوى جديد"><Plus size={16}/> مستوى جديد</button>}</div>
   <div className="grid-2">
    <section className="card"><div className="card-header"><div><div className="card-title">الفصول والشُعب الدراسية</div><div className="card-subtitle">السعة هي الحد الاستيعابي، ورقم القاعة وصف تشغيلي للشعبة.</div></div>{canManage&&<button className="btn btn-primary btn-sm" disabled={!level} onClick={()=>{setEditingSectionId(null);setSectionName("");setSectionCode("");setRoom("");setCapacity("35");setHomeroom("");setModal("section")}}><Plus size={15}/> إضافة شعبة</button>}</div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>الشعبة</th><th>القاعة</th><th>المسجلون / السعة</th><th>مربي/رائد الفصل</th><th>الإجراءات</th></tr></thead><tbody>{(level?.sections??[]).map(s=><tr key={String(s.id)}><td><strong>{s.name}</strong><div className="meta-text">{s.code}</div></td><td>{s.room_number??"—"}</td><td>{s.enrolled_count??s.students_count??0} من {s.capacity??"—"} طالب</td><td>{teacherName(s.homeroom_teacher_id)}</td><td>{canManage?<button className="btn btn-ghost btn-sm" onClick={()=>editSection(s)}><Edit3 size={13}/> تعديل</button>:<span className="meta-text">عرض فقط</span>}</td></tr>)}{(level?.sections?.length??0)===0&&<tr><td colSpan={5} style={{padding:24,textAlign:"center"}}>لا توجد شعب في هذا المستوى.</td></tr>}</tbody></table></div></section>
    <section className="card"><div className="card-header"><div><div className="card-title">المواد التعليمية</div><div className="card-subtitle">عدد الحصص الأسبوعية هو المطلوب أكاديميًا لهذا المستوى، ويُستخدم عند توزيع الجدول.</div></div>{canManage&&<button className="btn btn-primary btn-sm" disabled={!level} onClick={()=>{setEditingSubjectId(null);setSubjectName("");setSubjectCode("");setWeeklyPeriods("5");setModal("subject")}}><Plus size={15}/> إضافة مادة</button>}</div>{(level?.subjects??[]).map(s=><div className="feed-item" key={String(s.id)}><div style={{flex:1}}><strong>{s.name}</strong><div className="meta-text">{s.code}</div></div><span className="badge badge-blue">{s.weekly_periods??"غير محدد"} حصة / أسبوع</span>{canManage?<button className="btn btn-ghost btn-sm" onClick={()=>editSubject(s)}><Edit3 size={13}/> تعديل</button>:<span className="meta-text">عرض فقط</span>}</div>)}{(level?.subjects?.length??0)===0&&<div style={{padding:24,textAlign:"center"}}>لا توجد مواد مرتبطة بهذا المستوى.</div>}</section>
   </div>
  </>}
 </main><Footer/></div>
 {canManage&&modal&&<div className="modal-overlay" onClick={closeModal}><div className="modal" onClick={(e)=>e.stopPropagation()} style={{maxWidth:560}}><div className="modal-header"><div><div className="card-title">{modal==="level"?"إضافة مستوى دراسي":modal==="section"?(editingSectionId?"تعديل الشعبة":"إضافة شعبة جديدة"):(editingSubjectId?"تعديل المادة":"إضافة مادة")}</div><div className="card-subtitle">{modal!=="level"&&level?`المستوى: ${level.name}`:""}</div></div><button className="btn btn-ghost btn-sm" onClick={closeModal}><X size={18}/></button></div><div className="modal-body" style={{display:"grid",gap:10}}>
  {modal==="level"&&<><input className="form-input" placeholder="اسم المستوى — مثال: الصف السابع" value={levelName} onChange={(e)=>setLevelName(e.target.value)}/><input className="form-input" placeholder="الكود — مثال: G7" value={levelCode} onChange={(e)=>setLevelCode(e.target.value)}/></>}
  {modal==="section"&&<><input className="form-input" placeholder="اسم الشعبة — مثال: شعبة أ" value={sectionName} onChange={(e)=>setSectionName(e.target.value)}/><input className="form-input" placeholder="كود الشعبة — مثال: A" value={sectionCode} onChange={(e)=>setSectionCode(e.target.value)}/><input className="form-input" placeholder="رقم القاعة — مثال: A201" value={room} onChange={(e)=>setRoom(e.target.value)}/><input className="form-input" type="number" min="1" placeholder="السعة" value={capacity} onChange={(e)=>setCapacity(e.target.value)}/><select className="form-select" value={homeroom} onChange={(e)=>setHomeroom(e.target.value)}><option value="">بدون مربي/رائد حاليًا</option>{teachers.filter(t=>t.activeStatus==="active").map(t=><option key={t.id} value={t.id}>{t.name} — {t.specialization}</option>)}</select></>}
  {modal==="subject"&&<><input className="form-input" placeholder="اسم المادة" value={subjectName} onChange={(e)=>setSubjectName(e.target.value)}/><input className="form-input" placeholder="كود المادة" value={subjectCode} onChange={(e)=>setSubjectCode(e.target.value)}/><label className="small-readable">عدد الحصص الأسبوعية<input className="form-input" type="number" min="1" max="30" value={weeklyPeriods} onChange={(e)=>setWeeklyPeriods(e.target.value)}/></label></>}
 </div><div className="modal-footer"><button className="btn btn-ghost" onClick={closeModal}>إلغاء</button><button className="btn btn-primary" onClick={()=>void(modal==="level"?saveLevel():modal==="section"?saveSection():saveSubject())}>{modal==="level"?<><BookOpen size={15}/> إضافة المستوى</>:modal==="section"?<><Users size={15}/> {editingSectionId?"حفظ التعديلات":"إضافة الشعبة"}</>:<><BookOpen size={15}/> {editingSubjectId?"حفظ التعديلات":"إضافة المادة"}</>}</button></div></div></div>}
 </div>
}
