import type { DeliveryGateway, GatewayCommandResponse } from '../../application/delivery/contracts';
import type { DeliveryCommand, DeliveryState } from '../../application/delivery/types';
import { api } from '../api/client';
import { friendlyApiMessage } from '../api/errors';
import { asRecord, deliveryToApi, locationToApi, pricingToApi, proofToApi, shipmentFromApi } from '../api/mappers';
import { mockDeliveryGateway } from './mockDeliveryGateway';

const clientActionId = () => typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `web-${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function versionOf(path: string) { const r = await api.get<Record<string, unknown>>(path, { retries: 1 }); return Number(asRecord(r.data).version ?? asRecord(r.data).resource_version ?? 1); }
async function conversationSummary(id: string) { const rows = (await api.get<Record<string, unknown>[]>('/api/v1/conversations', { query: { page: 1, per_page: 100 } })).data ?? []; const found = rows.map(asRecord).find((x) => String(x.id) === id); if (!found) throw new Error('Conversation not found'); return found; }

async function execute(command: DeliveryCommand): Promise<GatewayCommandResponse> {
  try {
    const action = clientActionId();
    switch (command.type) {
      case 'shipment/assignDriver': await api.post('/api/v1/shipments/bulk-assign-driver', { driver_id: command.driverId, shipment_ids: command.shipmentIds, reason: 'dashboard_assignment' }); break;
      case 'shipment/transition': return { result: { ok: false, message: 'تغيير الحالة الرسمي يتم من خلال دورة التشغيل المعتمدة، وليس بتعديل مباشر للحالة.' } };
      case 'shipment/addAttempt': return { result: { ok: false, message: 'محاولات التسليم تُسجل من تطبيق المندوب وتحتاج اعتماد الشركة.' } };
      case 'shipment/import': return { result: { ok: false, message: 'استخدم استيراد CSV عبر Shipment Imports حتى يتم التحقق والمعالجة غير المتزامنة.' } };
      case 'shipment/requestSettlement': { const detail = shipmentFromApi((await api.get(`/api/v1/shipments/${command.shipmentIds[0]}`)).data); const today = new Date().toISOString().slice(0, 10); await api.post('/api/v1/settlements', { merchant_id: detail.merchantId, shipment_ids: command.shipmentIds, period_start: today, period_end: today, client_action_id: action }); break; }
      case 'pickup/approve': { const v = await versionOf(`/api/v1/pickup-requests/${command.taskId}`); await api.post(`/api/v1/pickup-requests/${command.taskId}/approve`, { resource_version: v, client_action_id: action, note: 'اعتماد من لوحة التحكم' }); break; }
      case 'pickup/review': { const v = await versionOf(`/api/v1/pickup-requests/${command.taskId}`); await api.post(`/api/v1/pickup-requests/${command.taskId}/review`, { decision: 'needs_review', review_note: 'تحتاج مراجعة تشغيلية', missing_shipment_ids: [], resource_version: v, client_action_id: action }); break; }
      case 'batch/assign': { const v = await versionOf(`/api/v1/dispatch-batches/${command.batchId}`); await api.post(`/api/v1/dispatch-batches/${command.batchId}/assign-driver`, { driver_id: command.driverId, resource_version: v, client_action_id: action, override_capacity: false }); break; }
      case 'driverUpdate/approve': { const v = await versionOf(`/api/v1/driver-updates/${command.updateId}`); await api.post(`/api/v1/driver-updates/${command.updateId}/approve`, { review_note: 'اعتماد من لوحة التحكم', resource_version: v, client_action_id: action }); break; }
      case 'driverUpdate/reject': { const v = await versionOf(`/api/v1/driver-updates/${command.updateId}`); await api.post(`/api/v1/driver-updates/${command.updateId}/reject`, { review_note: 'مرفوض للمراجعة', resource_version: v, client_action_id: action }); break; }
      case 'return/receiveAtHub': case 'return/markOutForMerchant': { const v = await versionOf(`/api/v1/return-cases/${command.returnCaseId}`); const suffix = command.type === 'return/receiveAtHub' ? 'receive-at-hub' : 'mark-out-for-merchant'; await api.post(`/api/v1/return-cases/${command.returnCaseId}/${suffix}`, { notes: 'Dashboard command', proof_file_ids: [], resource_version: v, client_action_id: action }); break; }
      case 'return/assignDriver': { const v = await versionOf(`/api/v1/return-cases/${command.returnCaseId}`); await api.post(`/api/v1/return-cases/${command.returnCaseId}/assign-driver`, { driver_id: command.driverId, notes: 'Dashboard assignment', proof_file_ids: [], resource_version: v, client_action_id: action }); break; }
      case 'return/confirmMerchantReceipt': { const v = await versionOf(`/api/v1/return-cases/${command.returnCaseId}`); await api.post(`/api/v1/return-cases/${command.returnCaseId}/confirm-return-to-merchant`, { notes: command.proofReference, proof_file_ids: [], resource_version: v, client_action_id: action }); break; }
      case 'barcode/create': { const created = await api.post<any>('/api/v1/intake-batches', { pickup_request_id: command.batch.pickupTaskId, merchant_id: command.batch.merchantId, expected_shipment_ids: command.batch.expectedShipmentIds, client_action_id: action }); return { result: { ok: true, message: 'تم إنشاء دفعة الاستلام.', createdId: String(asRecord(created.data).id ?? '') }, refresh: true }; }
      case 'barcode/scan': await api.post(`/api/v1/intake-batches/${command.batchId}/scan`, { barcode: command.shipmentId, scanned_at: new Date().toISOString(), client_action_id: action }); break;
      case 'barcode/undo': { const v = await versionOf(`/api/v1/intake-batches/${command.batchId}`); await api.post(`/api/v1/intake-batches/${command.batchId}/undo-last-scan`, { reason_code: 'operator_undo', resource_version: v, client_action_id: action }); break; }
      case 'barcode/close': { const raw = asRecord((await api.get(`/api/v1/intake-batches/${command.batchId}`)).data); const expected = Array.isArray(raw.expected_shipment_ids) ? raw.expected_shipment_ids.map(String) : []; const scanned = Array.isArray(raw.scanned_shipment_ids) ? raw.scanned_shipment_ids.map(String) : []; const missing = expected.filter((id) => !scanned.includes(id)); await api.post(`/api/v1/intake-batches/${command.batchId}/close`, { missing_shipment_ids: missing, unexpected_resolution: 'create_exception', resource_version: Number(raw.version ?? 1), client_action_id: action, note: 'إغلاق من لوحة التحكم' }); break; }
      case 'exception/resolve': { const ex = (await api.get<any[]>('/api/v1/exceptions', { query: { page: 1, per_page: 100, status: 'open' } })).data.find((x: any) => String(x.shipment_id ?? x.resource_id) === command.shipmentId); if (!ex) return { result: { ok: false, message: 'لم يتم العثور على استثناء مفتوح لهذه الشحنة.' } }; await api.post(`/api/v1/exceptions/${ex.id}/resolve`, { resolution_code: 'dashboard_resolved', note: command.resolution, command: command.driverId ? 'assign_driver' : null, command_payload: command.driverId ? { driver_id: command.driverId } : {}, resource_version: Number(ex.version ?? 1), client_action_id: action }); break; }
      case 'driver/upsert': { const d = command.driver; const body = { name: d.name, phone: d.phone, code: d.userCode || d.id || `DRV-${Date.now()}`, zone_id: d.zone || null, capacity: Math.max(1, d.capacity || 1), cash_limit_minor: Math.max(0, Math.round((d.pendingCash || 0) * 100)) }; if (d.id && !d.id.startsWith('new-') && !d.id.startsWith('DRV-')) await api.patch(`/api/v1/drivers/${d.id}`, body, { headers: { 'If-Match': '1' } }); else await api.post('/api/v1/drivers', body); break; }
      case 'driver/archive': { const v = await versionOf(`/api/v1/drivers/${command.driverId}`); await api.post(`/api/v1/drivers/${command.driverId}/suspend`, { reason_code: 'dashboard_suspend', notes: command.reason, resource_version: v, client_action_id: action }); break; }
      case 'driver/resetAccess': { await api.post(`/api/v1/drivers/${command.driverId}/reset-access`, { invalidate_sessions: command.invalidateSessions, force_password_change: command.forcePasswordChange, client_action_id: action }); break; }
      case 'merchant/upsert': { const m = command.merchant; const body = { brand_name: m.name, legal_name: m.name, contact_phone: m.phone, settlement_cycle: m.settlementCycle === 'twiceWeekly' ? 'twice_weekly' : m.settlementCycle, priority_level: m.priorityLevel }; if (m.id && !m.id.startsWith('new-') && !m.id.startsWith('MER-')) await api.patch(`/api/v1/merchants/${m.id}`, body, { headers: { 'If-Match': '1' } }); else await api.post('/api/v1/merchants', body); break; }
      case 'merchant/archive': { const v = await versionOf(`/api/v1/merchants/${command.merchantId}`); await api.post(`/api/v1/merchants/${command.merchantId}/archive`, { reason_code: 'dashboard_archive', notes: command.reason, resource_version: v, client_action_id: action }); break; }
      case 'settlement/create': { const s = shipmentFromApi((await api.get(`/api/v1/shipments/${command.shipmentIds[0]}`)).data); const today = new Date().toISOString().slice(0, 10); const created = await api.post<any>('/api/v1/settlements', { merchant_id: s.merchantId, shipment_ids: command.shipmentIds, period_start: today, period_end: today, client_action_id: action }); return { result: { ok: true, message: 'تم إنشاء التسوية وإرسالها للمراجعة.', createdId: String(asRecord(created.data).id ?? '') }, refresh: true }; }
      case 'settlement/approve': { const v = await versionOf(`/api/v1/settlements/${command.settlementId}`); await api.post(`/api/v1/settlements/${command.settlementId}/approve`, { note: 'اعتماد من لوحة التحكم', resource_version: v, client_action_id: action }); break; }
      case 'settlement/pay': { const v = await versionOf(`/api/v1/settlements/${command.settlementId}`); await api.post(`/api/v1/settlements/${command.settlementId}/pay`, { payment_reference: command.paymentReference, paid_at: new Date().toISOString(), payment_method: 'bank_transfer', resource_version: v, client_action_id: action }); break; }
      case 'finance/reconcileShipment': { const s = asRecord((await api.get(`/api/v1/shipments/${command.shipmentId}`)).data); await api.post(`/api/v1/finance/shipments/${command.shipmentId}/reconcile`, { remitted_minor: Math.round(command.remittedCash * 100), currency: s.currency ?? 'EGP', note: command.note, resource_version: Number(s.version ?? 1), client_action_id: action }); break; }
      case 'ledger/postAll': { const entries = (await api.get<any[]>('/api/v1/ledger/entries', { query: { page: 1, per_page: 100, status: 'pending' } })).data; await api.post('/api/v1/ledger/post', { entry_ids: entries.map((x: any) => x.id), posting_date: new Date().toISOString().slice(0, 10), note: 'ترحيل من لوحة التحكم', client_action_id: action }); break; }
      case 'period/close': { const periods = (await api.get<any[]>('/api/v1/accounting-periods', { query: { page: 1, per_page: 100 } })).data; const p = periods.find((x: any) => String(x.starts_on ?? '').slice(0, 7) === command.period || String(x.id) === command.period); if (!p) return { result: { ok: false, message: 'الفترة غير موجودة على الخادم.' } }; const end = String(p.ends_on ?? ''); if (!end) return { result: { ok: false, message: 'الفترة لا تحتوي تاريخ نهاية صالحًا.' } }; await api.post(`/api/v1/accounting-periods/${p.id}/close`, { closed_through: end, note: 'إغلاق من لوحة التحكم', resource_version: Number(p.version ?? 1), client_action_id: action }); break; }
      case 'settings/updateDelivery': { const cur = asRecord((await api.get('/api/v1/settings/delivery-policy')).data); await api.put('/api/v1/settings/delivery-policy', deliveryToApi(command.policy, cur, Number(cur.version ?? 1))); break; }
      case 'settings/updatePricing': { const cur = asRecord((await api.get('/api/v1/settings/pricing-policy')).data); await api.put('/api/v1/settings/pricing-policy', pricingToApi(command.policy, Number(cur.version ?? 1), String(cur.currency ?? 'EGP'), Number(cur.free_delivery_attempts ?? 3))); break; }
      case 'settings/updateProof': { const cur = asRecord((await api.get('/api/v1/settings/proof-policy')).data); await api.put('/api/v1/settings/proof-policy', proofToApi(command.policy, Number(cur.version ?? 1))); break; }
      case 'settings/updateLocation': { const cur = asRecord((await api.get('/api/v1/settings/location-policy')).data); await api.put('/api/v1/settings/location-policy', locationToApi(command.policy, Number(cur.version ?? 1))); break; }
      case 'settings/updatePrinting': case 'settings/updateNotifications': break;
      case 'chat/send': await api.post(`/api/v1/conversations/${command.roomId}/messages`, { message_type: command.note ? 'internal_note' : 'text', body: command.text, client_action_id: action }); break;
      case 'chat/toggle': { const room = await conversationSummary(command.roomId); const v = Number(room.version ?? 1); const endpoint = String(room.status) === 'closed' ? 'reopen' : 'close'; await api.post(`/api/v1/conversations/${command.roomId}/${endpoint}`, { resource_version: v, client_action_id: action, note: endpoint === 'close' ? 'إغلاق من لوحة التحكم' : 'إعادة فتح من لوحة التحكم' }); break; }
      case 'chat/transfer': { const room = await conversationSummary(command.roomId); await api.post(`/api/v1/conversations/${command.roomId}/transfer`, { assignee_user_id: command.assignedTo, resource_version: Number(room.version ?? 1), client_action_id: action }); break; }
      case 'chat/read': await api.post(`/api/v1/conversations/${command.roomId}/read`, { last_read_message_id: null }); break;
    }
    return { result: { ok: true, message: 'تم تنفيذ العملية بنجاح.' }, refresh: true };
  } catch (error) { return { result: { ok: false, message: friendlyApiMessage(error) } }; }
}

export const apiDeliveryGateway: DeliveryGateway = {
  load(): Promise<DeliveryState> {
    return mockDeliveryGateway.load();
  },
  execute,
};
